### ISSUE TITLE
Compile runtime using TypeScript, remove npm install calls from racks

### ISSUE THREAD

**Issue by glebm** [vishesh/racketscript#103]
The goal is to let us gradually switch to TypeScript. This will also massively improve `racks` compilation times by avoiding `npm install` entirely.

- [ ] Make racks compile using TypeScript and accept the important [tsc arguments](https://www.typescriptlang.org/docs/handbook/compiler-options.html) (`--target`, `--module`, `--moduleResolution`). This should be possible with few code changes and without converting any code to TypeScript.
- [ ] Run `npm install` on setup to install TypeScript and HAMT.
- [ ] Remove the babel/traceur/traceur-browser code.
- [ ] Update the playground to use e.g. [system](https://github.com/systemjs/systemjs) (or commonjs, or amd, TypeScript can output all of them) instead of traceur.

**Comment by vishesh** [comment]
Before you dive into this, I will list out few other things that affect this task:

- Our long term goal is to write most of runtime in RacketScript itself. Our first step was moving kernel to `kernel.rkt` which is mostly done. This probably wont happen this year, but will most likely happen.
- One of the reasons we didn't rewrite corelib in RacketScript was because we also wanted to explore other options of encoding these primitives (for example Urlang[0] uses tagged arrays). That is great work, and it would be worthwhile to do some research and experiments on this before we spend our time on this or RacketScript rewrite.

Some of the questions I've on this:

- Does TypeScript do dead-code eliminations and other kind of optimizations?
- Can TypeScript link these with our compiled ES6 modules?
- How much adding type annotation would actually help us? Most of the code is fairly straightforward and self-contained in corelib. Following a simple HTDP[1] design recipe as guideline IMO is ok for now.
- Do you have a timeline and estimate an how much changes would be required? 
- This will also require a change in our testing strategy (in fixtures, which is not really an issue here, but something to be listed).

I'm glad you are looking into improving the corelib, and it definitely needs some improvement. However, at its current state it is sufficiently stable to follow other tasks. A major overhaul is something I worry may introduce new bugs and affect those tasks which IMO require more immediate attention. Some of those around runtime include:

1. Support Racket numbers.
2. Implementing more Racket kernel functions in `kernel.rkt`.
3. Adding contracts to `kernel.rkt` primitives.
4. Benchmarks.
5. Exploring whether we should use Racket library, or write our own subset of collect library. For example, `in-string` was one of those examples which stopped us from using native representation. What are the parts in Racket library that are impossible for us to do, e.g. 
6. Racket vs JavaScript regexp. This is not immediately required, but it is self-contained.
7. Better string/bytes/... support which you already helped with a lot!
8. Fixtures and testing framework - (e.g #100 #79 #18 #17 #6 #18)
9. Explore applications based on top of RacketScript (E.g. big-bang). This may seems unimportant, but I can't emphasize enough how important this is, and I'm unsuccessfully trying to spend more time on this. You made a contribution here by porting Waxeye!
10. Improve `racks` compiler #14  (not related to runtime, but very self-contained): I think some improvements there should improve the compilation time. `npm install` main bottleneck is gone after first install. Another thing I've been looking into was to convert `racks` to more like a `raco` like utility.

Overall, unless there is a really strong reason, I would appreciate contributions toward above tasks. We can look for more if these don't interest you.

[0] https://github.com/soegaard/urlang
[1] http://www.ccs.neu.edu/home/matthias/HtDP2e/index.html [I think somewhere there is whole design recipe]

**Comment by glebm** [comment]
> Our long term goal is to write most of runtime in RacketScript itself

It's easier to read and maintain JavaScript written in JavaScript / TypeScript than in a lispy DSL, especially for complex code. Far more potential contributors are familiar with JavaScript than the RacketScript DSL (the `#js` and `$` stuff). Of course, for simple functions like the current code in kernel.rkt it doesn't matter. It does matter for actual data structures and algorithms.

> Does TypeScript do dead-code eliminations and other kind of optimizations?
> Can TypeScript link these with our compiled ES6 modules?

No and no, and it shouldn't. Dead code elimination should not be a concern of this project! I'll explain.

As long as it generates modular code, dead code elimination is done by tools specialized in this (such as Webpack and UglifyJS), as the last step of bundling a production project. These tools use advanced techniques, such as tree-shaking and effect detection, to achieve the goal.

TypeScript *does* annotate some of its output with known effects to help the downstream tools do a better job there, see e.g. https://github.com/Microsoft/TypeScript/issues/13721.
If you have a novel technique in mind for dead code elimination, it'd be better for everyone if you contribute it to an existing project specialized in dead code elimination. If the technique requires knowledge of semantics available only on the RacketScript side, that information can be exported with annotations.

> How much adding type annotation would actually help us? Most of the code is fairly straightforward and self-contained in corelib. Following a simple HTDP[1] design recipe as guideline IMO is ok for now.

Type annotations make the code far easier to follow, greatly improve development speed, prevent several classes of bugs, and make it easier for engineers new to the project to contribute.

While working on the PRs I've worked on, the rudimentary JSDoc type annotations have *already* saved me a ton of time.

> Do you have a timeline and estimate an how much changes would be required?

I could probably do it in a few evenings and then a week or two for answering review comments :sweat_smile: (seriously though I'd appreciate less perfectionism and nitpicking, and more active code crunching at this experimental stage in the project life -- I think it would get RacketScript to a much more complete state much faster -- but I understand that's just like, my opinion, but it's based on a ton of experience of starting, contributing to, and finishing open source projects).

> This will also require a change in our testing strategy (in fixtures, which is not really an issue here, but something to be listed).

I don't think what I've outlined will affect the tests at all. Why do you think this?

> However, at its current state it is sufficiently stable to follow other tasks.

I want to use RacketScript for actual Racket code, today! This means implementing a bit more of the standard library. My priorities are different. Which is fine, that's how open source projects thrive, with diversity.

> A major overhaul is something I worry may introduce new bugs and affect those tasks which IMO require more immediate attention.

Types make you brave. Types help prevent bugs and make refactorings and overhauls easier. There is a lot of synergy you would get from this for these other tasks you consider higher-priority.

Besides, I'm not talking about redesigning anything, just a few bits that will be necessary when rewriting the current implementation to use TypeScript. Also, the RacketScript runtime already has decent test coverage. Thanks for that and I wouldn't even consider contributing otherwise!

**Comment by vishesh** [comment]
> It's easier to read and maintain JavaScript written in JavaScript / TypeScript than in a lispy DSL [...]

Racketeers beg to differ and this is pretty much Racket. In any case, if that is true, the answer is not JavaScript/TypeScript improving RacketScript. There are solid but easy ways around the verbose FFI (new `#lang`).  Moving kernel was already a good decision. So one way or another, corelib in RacketScript will happen!

I don't think anyone here needs an introduction to type systems and its advantages. These are engineering decisions made from experience working on this project, not based on how I feel towards static or dynamic types. From what it seems, with discipline and layered approach of writing corelib (I believe its not hard to do so with corelib. There are programs where it is hard otherwise), the benefits are not much. Regardless, even if I'm wrong about benefits of types for corelib case, we are moving on migrating to RacketScript so it doesn't matter.

If I'm still terribly wrong, I would someday would like to dogfood Racket ecosystem and see @stchang Turnstile to be used to typecheck core if necessary.

>  I'd appreciate less perfectionism and nitpicking, and more active code crunching [...]

I'm sorry if you feel that way, but I don't have to list the advantages of CR. In the end I'm also guilty of trying to minimize my future homework created by rushed out design/code .

> I want to use RacketScript for actual Racket code, today! This means implementing a bit more of the standard library.

Yes I appreciate that. But I don't think TypeScript or other cosmetic changes to existing corelib is going to solve that. Its more kernel primitive functions in `kernel.rkt`. I'm not saying I don't welcome those changes as they do improve the overall quality of software. I'm just making point that if you want to use RacketScript today, you need more kernel primitives.

**Comment by stchang** [comment]
The fact that the benefits of TypeScript here are unclear enough to warrant a long discussion indicates to me that it's probably not worth the effort.

I think RacketScript needs to be focusing on adding concrete features right now. If switching to TypeScript directly enabled some feature X of Racket, eg tail calls or contracts, that would be a much more persuasive argument.

But as it is, the justifications seem to be the standard high-level arguments for types (and the disadvantages that come along with it), which most people are familiar with. After all, RacketScript is implemented with Typed Racket so it's clearly not too stubborn about any one side of the types debate.

Other thoughts:
- Would the standard arguments for types even apply here since TypeScript would mostly be used as an intermediate language? For example we wouldnt get as much benefit from the tools support.
- Are there Racket idioms inexpressible or much more verbose with the typed language, eg does it support full occurrence typing? This suggests waiting until more features of racket are supported before possibly revisiting the TypeScript option.
- Finally, Typescript's type system doesnt actually make any guarantees right? And IIRC the unsoundness cases involve higher order functions, which are pretty common when compiling a functional language. So the bugs it catches are probably fairly basic and would be caught by runtime checks anyways.

**Comment by glebm** [comment]
> The fact that the benefits of TypeScript here are unclear enough to warrant a long discussion indicates to me that it's probably not worth the effort.

TypeScript, even without types (even if we just run it over JS files), can replace 3 different tools (gulp, babel, traceur) with one, making the compilation pipeline much simpler. It does not do polyfills, but as discussed, RacketScript should not be doing these anyway.

TypeScript can compile our code to any of the following module systems, "None", "CommonJS", "AMD", "System", "UMD", "ES6", "ES2015" or "ESNext", either as one file or separate files.

This pretty much covers all our needs.

> Are there Racket idioms inexpressible or much more verbose with the typed language, eg does it support full occurrence typing?

TypeScript is static typing only, it doesn't add any runtime overhead, and so does not support full occurrence typing.

It does support: union types, structural subtyping, generics, null checking, [string literal types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#string-literal-types), [index types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#index-types), the [bottom type](https://www.typescriptlang.org/docs/handbook/basic-types.html#never), [user-defined type guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards), and many more.

TypeScript is gradual typing, though, so you don't *have to* add types if there is a case that's not supported. However, the current codebase does not seem to contain any such cases.

> Finally, Typescript's type system doesnt actually make any guarantees right? And IIRC the unsoundness cases involve higher order functions, which are pretty common when compiling a functional language.

The generated code would not be typechecked by TypeScript, I'm only proposing it for the runtime only (or parts of it, or even none at all).

For the runtime, pragmatically, what TypeScript checks is very useful. Do not dismiss it just because it's unsound, the unsoundness is an extremely rare edge-case in real code. It also evolved considerably recently.

The first example in the Racket docs you've linked can be done trivially:

```typescript
function flexibleLength(strOrLst: UString | List<Any>): number {
  if (UString.check(strOrLst)) {
    // user-defined type guard applies type-narrowing
    return stringLength(strOrLst);
  } else {
    return listLength(strOrLst);
  }
}

// UString.check would be defined like this:
function check(v: any): x is UString {
    // the return type is a user-defined type guard, i.e. we tell the compiler
    // to trust us that: if this function returns true, x *must* be a UString.
    return v instanceof UString;
}
```

Here is a few more examples of the type system features, including interfaces, user-defined type guards, and intersection types:

```typescript
class Pair {
  hd: any;
  tl: any;
  // ...
}

interface List<T> {
  hd: List<T>;
  tl: List<T> | Empty;
}

function check(v: any): x is Pair {
    return v instanceof Pair;
}

function isList(x: any): x is (Pair & List<Any>) {
    return v === Empty || (check(v) && v._listLength !== false);
}

function length(x: (Pair & List) | Empty) {
  return x.length;
}

function someStuff(x: any) {
  if (isList(x)) {
    // Within this if, the type of x is narrowed to (Pair & List<Any>).
  }
}
```

**Comment by vishesh** [comment]
I don't see how my and @stchang concerns, and well as its alignment with future goals of project are addressed here. Any of those module systems can be produced using Babel or Traceur.

Overall from the discussion:

- There is no clear indicator from current state of things that static types are necessary to productively work on **this** project.
- We need to be focusing our time on writing and reviewing concrete features.
- From our experience working with both statically and dynamically typed part of this codebase, a lot of these modules are fairly simple, and with good simple practices its manageable keep their contracts correct with no extra effort.
- How many bugs in past could have been caught using type system in corelib? I don't recall any frustrating day, when I said to myself that I really need types for this. The way project is moving forward I don't see those days happening in near future.
- We want to migrate mostly to RacketScript. Whenever that happens, any work here goes to trash.

Considering above points, whatever benefit we gain is most likely not worth the time and effort spent implementing it. Decision here are not based on listing textbook pros and cons of static/dynamic types, but its relevance in a project, our goals, our experience and foresight and engineering trade-offs.

I must therefore decline this task.

**Comment by stchang** [comment]
Before this issue, I would not have considered TypeScript as even a possible option. But you motivated me to read up a little more and it's more mature than I had thought, so thanks for that. And do keep the suggestions coming.

I think the original point still stands though, which is that it's not a clear-cut "just drop in TS and win" decision. Since we are still trying to determine the feasibility of this project as a whole, now is probably not the best time to commit (our few) resources to experimenting with different back ends in order to achieve (relatively) minor improvements.

Some more thoughts after reading the clarification points:
- If only the runtime is type checked, then we rely on the properties of the gradual typing system. A sound gradual type system like in Typed Racket inserts dynamic checks when untyped code imports typed code in order to preserve the type system's guarantees. I do not think TypeScript does this? This would mean that untyped user Racketscript code can completely ignore the types in the runtime, further reducing the benefits of the type system?
- Implementing the runtime in TS conflicts with the decision to implement as much of the runtime as possible in RacketScript itself. This is important because we still trying to figure out how much of Racket is even feasible to compile to JavaScript, so we need as much example code as possible. It may be that we need to revisit this decision later but I think it's the right one for now.

**Comment by bennn** [comment]
> I do not think TypeScript does this?

Right, TypeScript does not insert runtime checks. It's just static analysis.
Still useful! But you need to reason about TypeScript programs as JavaScript programs.
