### ISSUE TITLE
`(#js.express.static)` compiles to `express.rstatic()`

### ISSUE THREAD

**Issue by glebm** [vishesh/racketscript#123]
This breaks the playground.
Perhaps keyword renaming is too eager.

**Comment by glebm** [comment]
Also getting `rthis` in image.rkt

**Comment by vishesh** [comment]
Yeah. The renaming thing was a quick temporary fix and I expected it to break some FFI stuff (624a2c2c5b608afd366a2647993d466828997fe2). I'm slowly working towards handling the whole identifier thing more appropriately. There is some other major refactoring involved unfortunately.

`this` can be fixed by using `$/this` from interop library instead of unsafe `#js*.this`. I will push a fix for rstatic thing.

**Comment by vishesh** [comment]
Closing this. HTDP is still broken though.
