### ISSUE TITLE
"make" in GitHub Repository Fails for Test Cases

### ISSUE THREAD

**Issue by 7enderhead** [vishesh/racketscript#137]
- initial 'make' cannot build its test target since racketscript/compiler/* modules are not yet installed:
  - filaure in fixture.rkt, line 7
- after 'make setup', rerunning 'make' then works

**Comment by vishesh** [comment]
Hi @7enderhead, ideally if you are not developing RacketScript you don't need to use `make`. You can try using `raco pkg install racketscript`.

Running `make setup` before `make` is expected behavior and is documented [here](https://github.com/vishesh/racketscript#install-from-github). Maybe with slight tweak to `setup` we can make it depend on `build` but the default one re-installs if it already exists (which we do not want with every build).

**Comment by glebm** [comment]
There is a PR with corrected make dependencies here #118 but it was rejected.

**Comment by vishesh** [comment]
I'll close this as this is an expected behavior.
