### ISSUE TITLE
unifying implementation of exceptions

### ISSUE THREAD

**Issue by stchang** [vishesh/racketscript#152]
Currently, I think `error` compiles to `throw`, but from what I can tell, nothing compiles to `catch`. I think this means that I can't write tests that expect an error?

Separately, there is the (still experimental?) `raise`, which can be caught using `with-handlers`, both of which compile to an implementation of continuation marks.

Was the plan to have the second continuation-marks-based implementation be the eventual default case?

While implementing tests, I've so far skipped writing tests that expect an error but it would be good to enable them at some point.

**Comment by vishesh** [comment]
I think catching errors should work as they should all be based on `with-handlers`. IIRC, exceptions in Racket use `abort-current-continuation` which uses a `throw`[1], and that exception is handled by a try-catch block in `call-with-continuation-prompt`[2]. I think the reason catching `error` doesn't work is because it doesn't throw the `AbortCurrentContinuation`. Another problem however may be that `error` doesn't provide a tag to match against. 

[1] https://github.com/vishesh/racketscript/blob/master/racketscript-compiler/racketscript/compiler/runtime/kernel.rkt#L834
[2] https://github.com/vishesh/racketscript/blob/master/racketscript-compiler/racketscript/compiler/runtime/core/marks.js#L97

**Comment by stchang** [comment]
Ok I see maybe it's not as different as I originally thought. But `error` should still be catchable right? So should `error` set a mark like what [`raise`](https://github.com/vishesh/racketscript/blob/master/racketscript-compiler/racketscript/compiler/runtime/kernel.rkt#L843) does?

**Comment by vishesh** [comment]
Oh yes, so now I remember (I think). `with-handler` uses this specific tag name `#js.Paramz.ExceptionHandlerKey` so I think if `error` implementation does what `raise` does it should all just work.

**Comment by stchang** [comment]
> if `error` implementation does what `raise` does it should all just work.

Ok good! That's what I'm trying to do. Glad to be on the same page.
