### ISSUE TITLE
fix and run ffi tests

### ISSUE THREAD

**Issue by stchang** [vishesh/racketscript#227]
I was looking into pr https://github.com/vishesh/racketscript/pull/226 and I realized the ffi tests are not running (and currently dont work)

**Comment by vishesh** [comment]
Yes, its been an issue for while. https://github.com/vishesh/racketscript/issues/100

**Comment by stchang** [comment]
ah forgot about that issue. I was thinking those tests can be run outside the fixture, since we don't really want to compare with Racket anyways right?

**Comment by vishesh** [comment]
Yes, Can be a separate script I think to keep things simple. Or we can just add a special test kind (check) for FFI, which just runs the compiled FFI code in NodeJS and ignores Racket.

**Comment by stchang** [comment]
Is it worth looking into any js testing frameworks, or do you think they'll be too heavyweight?

**Comment by samth** [comment]
I recently have learned some about js testing frameworks and they were all bad.

**Comment by samth** [comment]
But I think "mocha" is the one that's most popular/useful for this kind of thing, particularly when not caring about the browser.

**Comment by vishesh** [comment]
I don't think we need to use any framework for now. I think we can test a lot by adding unit-tests that just take some RacketScript code and convert it to JS, and just compare it against what we expect. The reason is that it is an unsafe FFI and we don't usually add any checks when we cross boundaries. For other stuff, maybe just call NodeJS and evaluate the JS?
