### ISSUE TITLE
(runtime) error: ReferenceError: $traceurRuntime is not defined

### ISSUE THREAD

**Issue by bentxt** [vishesh/racketscript#54]
I've uninstalled the last racketscript installation because '--target babel' always gave me runtime errors. Now racketscript is installed again from source with:

- 'make setup'
- 'npm install -g traceur gulp'

Compiling to *.js  seems to work

~~~~~~~
> racks for.rkt 
[...]
npm WARN racketscript@0.0.1 No license field.
[11:42:33] Using gulpfile ~/local/racketscript/git/racketscript/js-build/gulpfile.js
[...]
[info] Finished.
~~~~~~~

But I can't resolve this runtime error: 
> node js-build/dist/compiled.js

ReferenceError: $traceurRuntime is not defined

**Comment by vishesh** [comment]
Hi, I was aware of one issue that was involved around Babel and fixed in current master `3d221e2284f1312fdc38d50be7b4bb462c23024e`. Please let me know if you are still facing the issue with the error message/traceback you are getting.

Regarding Traceur -

- If you are using Traceur target, you need to include traceur runtime. The RacketScript produces a separate file called `bootstrap.js` in js-build directory which you can invoke using NodeJs. It is documented in [Traceur](https://github.com/vishesh/racketscript#traceur) section but I think I should include that in README.
- Alternatively, if you are trying to run your program in web-browser either use the `traceue-browser` target or you can manually include the Traceur runtime like in [this example](https://github.com/vishesh/racketscript-playground/blob/master/static/index.html#L47).
- Lastly you can also use the `traceur` executable installed by the traceur NPM package to run the ES6 files directly in js-build/modules/* folder.

BTW, thank you for trying RacketScript! Wish you had a smoother start.

**Comment by bentxt** [comment]
>If you are using Traceur target, you need to include traceur runtime. 

According to the README, the traceur runtime is only needed in a browser context.

> The RacketScript produces a separate file called bootstrap.js in js-build directory which you can invoke using NodeJs. It is documented in Traceur section but I think I should include that in README.

It would be nice to add to end-to-end examples: one for traceur, one for babel.

BTW, I can no longer reproduce my own error ... It works now

**Comment by vishesh** [comment]
Seems like the doc is little ambiguous. Thanks for pointing out! Created #56
