### ISSUE TITLE
Porting forward.scm to RacketScript

### ISSUE THREAD

**Issue by amirouche** [vishesh/racketscript#61]
I created a minimalist scheme framework for creating web apps in scheme using the BiwaScheme interpreter called [forward.scm](https://github.com/amirouche/forward.scm). Basically, it boils down to the [`%create-app`](https://github.com/amirouche/forward.scm/blob/master/forward.scm#L184) procedure.

It's similar in principle to redux, it use a virtualdom library called snabbdom (similar in principle to reactjs) and prolly similar in principle to ClojureScript's om (even though I don't have om experience yet).

To make a port to RacketScript (RS) possible I need to know two things:

- How to call javascript from RS and vice-versa
- Right now, the framework works with the assumption that XHR calls are not callback based, they are not synchronous tho. This is made possible thanks to BiwaScheme's magic [`http-request`](https://github.com/biwascheme/biwascheme/blob/master/src/library/webscheme_lib.js#L462) which AFAIU use somekind of `call/cc`. Now I now RS doesn't implement call/cc (why?). I successfully ported forward.scm to use the new [`async`/`await` from ES2017](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await). My question is: does RS plan to support somekind of `call/cc` similar to biwascheme? Does it support `async`/`await`?

Thanks!

**Comment by vishesh** [comment]
This sounds like great library for RacketScript!

> How to call javascript from RS and vice-versa

I've not documented the interop yet, but the API is implemented here[1]. It may not be obvious on how to use that just from that, so you can look at these[2][3][4][5] modules which make use of the FFI. Finally our runtime library[5] makes uses FFI quite a lot. If these modules are not readable, I can quickly write a documentation for FFI. Although due to experimental nature of RacketScript, it is subjected to change (not drastically though). Suggestions/feedback for improving FFI are welcome!

Regarding `call/cc`, there are no plans to implement that right now as RacketScript is a source-to-source compiler that uses JavaScript stack instead of manually managing the stack (I think since Biwascheme is an interpreter it manually manages the stack).

ES6 `async/await` is not yet implemented in compiler, but its trivial to add this if RacketScript simply plans to rely on Babel/Traceur to compile it to ES5 (or whatever that is supported by browsers/node). If you decide to make your library work for RacketScript, I would be happy to make a patch to support this.

[1] https://github.com/vishesh/racketscript/blob/master/racketscript-compiler/racketscript/interop.rkt
[2] https://github.com/vishesh/racketscript/blob/master/racketscript-extras/racketscript/private/jscommon.rkt
[3] https://github.com/vishesh/racketscript/blob/master/racketscript-extras/racketscript/htdp/image.rkt
[4] https://github.com/vishesh/racketscript/blob/master/racketscript-extras/racketscript/htdp/universe.rkt
[5] https://github.com/vishesh/racketscript/blob/master/racketscript-compiler/racketscript/compiler/runtime/kernel.rkt

**Comment by amirouche** [comment]
tx, I will look into it.

**Comment by amirouche** [comment]
My understanding is that I need to use `#js*.something` to have access to variable something in javascript.

Is there a `alist->JSObject` and `list->JSArray` kind of procedures?

**Comment by amirouche** [comment]
Also, how do you pass a procedure as callback to javascript?

Sorry, I read the links you provided but I did understand much. I am getting started in racket, I know Scheme via GNU Guile, tho.

**Comment by vishesh** [comment]
`#js*.something` will not check if identifier "something" actually
exists (i.e. not a free variable), while `#js.something` will throw
error if its free variable. Latter is recommended.

Regarding data conversions there are some macros:

    ($/array "a" "b" "c" "d"...) ;;==> ["a", "b", "c", "d"]
    ($/obj ["a" 1] ["b" 2] ["c" 3]) ;; => {"a": 1, "b": 2, "c": 3}

These are macros not functions and will produce the exact JS literal.
Since these are macros you cannot use them like:

    (apply $/array '(1 2 3 4)) ;;=> error

or, pass `$/array` or `$/obj` as values to other functions. I will see
if I can fix this by this week, but otherwise an easy way is that you
can wrap this around your own function to get over it. For example,
`assocs->obj`[1] function here does that.

[1] https://github.com/vishesh/racketscript/blob/master/racketscript-compiler/racketscript/interop.rkt#L173

**Comment by vishesh** [comment]
Regarding passing procedures as callbacks, its same as passing any function. Racket functions translate exactly as JavaScript function. For example (taking example from RacketScript Playground) the following code simply passes a lambda for `ready` callback. You could have named that lambda using `(define foo-cb ...)` and replace the whole lambda with `foo-cb` instead.

```
(let ([jquery #js*.jQuery])
  ($> (jquery document)
      (ready
       (λ ()
         ($> (jquery "body")
             (css "margin" 0)
             (css "padding" 0))
         (print-image (welcome-image))))))
```

`$>` is a chaining operation typical in JS.

```
($> (jquery "body") 
       (css "margin" 0)
       (css "padding" 0)) 
;;=> jquery("body").css("margin", 0).css("padding", 0)       
```
If you want to do a ref/index operation:

```
(define x ($/obj ["a" 1]))
(displayln ($ x 'a))
;;=> displayln(x.a)
(displayln ($ x foo())
;;=> displayln(x[foo()])
(displayln ($ x 1)
;;=> displayln(x[1])

;; Same rules apply to arrays.
```

Hope this helps.

**Comment by vishesh** [comment]
Please re-open or create new ticket if have any more questions.
