### ISSUE TITLE
Strings should be Unicode codepoints (not UTF-16 chars)

### ISSUE THREAD

**Issue by glebm** [vishesh/racketscript#69]
Racket strings are semantically lists of Unicode codepoints.

RacketScript strings seem to be lists of UTF-16 chars (like JavaScript strings).
This will cause incompatibility issues in any code that does heavy string processing, such as parsers.

A simple test for this is:

```racket
#lang racket/base
(displayln (string-length "😃"))
; Expected: 1; Actual: 2
```

**Comment by vishesh** [comment]
Thanks for the bug report!

As self-reminder, RacketScript doesn't implement mutable strings as well which can be easily done with a fix for this.

**Comment by glebm** [comment]
Going to give this a go.

**Comment by vishesh** [comment]
Cool. Let us also discuss the potential solutions here before implementing. I'll list out some the questions I had in mind:

1. Do we need to implement a new class for strings to properly support Racket strings or we can just implement the library functions which do the right thing (e.g. fix `string-length`).
2. If we implement class which keeps an array of chars what kind of performance hit we will take? What about supporting regexp in this case? Printing will take hit as well because of join each time, and hence rendering I think.
3. How do we implement mutable strings? We can have a separate implementation for mutable strings I think.

**Comment by glebm** [comment]
Basic points:

1. New class. Otherwise simple operations such as indexing will become `O(n)`.
2. There are ways to optimize this.
3. Yes, a separate implementation.

I think it will be far easier to discuss once I have some working code.

I don't know much about about transpilers, but I know more about string encoding and handling than any sane person should aspire to learn.

The code will be faster to write and easier to read than a design doc.

**Comment by vishesh** [comment]
The runtime complexity isn't a problem but the constant factor. But yes, we should focus on correctness for this right now. It may help to see how other compilers are doing. Eg. Clojurescript seems to be in our situation where they use native strings but correct implementation of library functions [1]

[1] https://groups.google.com/forum/#!topic/clojure/L8mLwNX0oKs

**Comment by glebm** [comment]
@vishesh I think that Clojure strings are not Unicode codepoints but UTF-16 code units, at least on Java.
