### ISSUE TITLE
Converting JavaScript objects to Racket (in #lang racketscript/base code)

### ISSUE THREAD

**Issue by glebm** [vishesh/racketscript#72]
1. How can I convert a JavaScript Array to a Racket list (or vector, or something)?
2. How can I convert a JavaScript String to a Racket string?

**Comment by vishesh** [comment]
1. We do this everywhere in runtime, but have not exposed it to FFI yet. Mainly because the use never came up, and FFI is not really finalized. This is a weekend and its easy change, so I can get this done after work today.
2. Right now, Racket strings are converted to JavaScript strings (which are not semantically not same because of immutability and unicode stuff you filed). Which also means you will not have to convert them right now.

**Comment by glebm** [comment]
@vishesh Thanks, that's what I figured while working on #73 :+1:

**Comment by vishesh** [comment]
Cool!

The issues still exist and will be address in #74.
