### ISSUE TITLE
JavaScript style: Module names should be camelCase, not PascalCase?

### ISSUE THREAD

**Issue by glebm** [vishesh/racketscript#76]
This is a far more common style, what do you think?

We can suffix or prefix them with `mod` to avoid clashes with other identifier names.

As it is now, it's a bit confusing because there is e.g. `Pair` but also `Pair.Pair`.

**Comment by vishesh** [comment]
Sure if its ubiquitous. However, the existing code should be refactored as soon as we start otherwise it just stays like that forever. Would you be willing to work on this?

**Comment by glebm** [comment]
On the other hand, an even more common style is default exports or named imports only (no `*`), neither of which is going to be easy to refactor, so I'm closing this. Doesn't matter that much.

**Comment by vishesh** [comment]
The reason we use `*` is to be able to pass around modules which have a common interface. I think `*` is good here because instead of `makeList`, `checkList`, `makeVector`, `checkVector` I think `List.make`, `Vector.make` etc  more readable. The second benefit is it provides some abstraction for free, as in I can just pass the module object and we can get the `make` or `check` functions. Kind of like a class with all static methods, but since we are not forced to use classes (like in Java) we can just use modules instead.
