### ISSUE TITLE
Replace HAMT with a native Map

### ISSUE THREAD

**Issue by glebm** [vishesh/racketscript#90]
Addressing:

> On side note, please file/ask a discussion ticket before taking up bigger changes. This will let us discuss design decisions prior, avoid any duplicated efforts and hence save time.

This is something I want to do because a native Map is *much* faster.

The native `Map` can only store primitive values, so we can have two maps internally,
one for `Map<hash, Array<Primitive|Uint8Array>>` and another for a map of JS primitives.

The implementation will be tiny and likely on the order of 100x faster than using HAMT, though microbenchmarks here would be nice.

Doing this will also mean we no longer have any third-party dependencies, which has advantages such as making migration to `TypeScript` easier.

**Comment by glebm** [comment]
This would also allow for a trivial implementation of `make-weak-hash` functions.

**Comment by vishesh** [comment]
Yes we needed some specialization around hash. One quick no-brainer is mutable-hash-eq can simply be native Map.

However, I'm not entirely sure about next two points.

1. How are you going to achieve immutability using native Maps?
2. How is HAMT stopping us from migrating to `TypeScript`? Its untyped, but I think we can add type annotations when importing HAMT functions, and we can typecheck our code.

Lastly, since FFI is not finalized, we don't yet have a decision on what the behavior of primitives should be when used with Racket hash. We may want to have a notion for `eq?`, `eqv?` and `equal?` for those values as well. If someone wants immutable JS kind of equality they can use `hasheq`.

**Comment by glebm** [comment]
> How are you going to achieve immutability using native Maps?

Ooh, I hadn't realized that Racket maps are persistent.
Nevermind then :)

> How is HAMT stopping us from migrating to TypeScript?

It's not, it's just easier to have everything in typescript rather than write type definitions.

However, there are TypeScript versions of hamt.
